# Student Attendance Data Cleaning and ISP Data

Students that have been enrolled in ISP of any form have been showing up in duplicates in the Aeries query for attendance. Using this code, students that have duplicates will be cleaned by:
1) Separating them from the non duplicates.
2) Determining if they have completed, are in progress, or are incomplete in ISP.
3) Data will then be cleaned up depending on what category they are under.

Once the data has been cleaned for ISP students they will be rejoined with the rest of the students to produce a master attendance file that no longer has duplicates along with other sheets that give calculations on the number of students for each category at all of the school sites along with a list of students in progress and incomplete.

The Aeries query to obtain the data used for this file is (adjust the year in the query for the current school year):

LIST AHS STU STU.SC STU.NM STU.ID STU.GR AHS.YR AHS.EN AHS.PR AHS.AB AHS.AE AHS.AU AHS.TD AHS.TRU AHS.SU AHS.ISS AHS.ISC AHS.ISI IF AHS.YR = 2022-2023

__Make sure to scroll to the bottom to look over the checks on possible special situations that you might have to look into about the data.__

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Place the destination that is desired for the generated file to output
output_final = "C:\\Users\\derek.castleman\\Desktop\\Attendance2022to2023.xlsx"

In [3]:
# Copy the file pathway from the Aeries query into the parenthesis
attendance = pd.read_excel(r"C:\Users\derek.castleman\Desktop\AttendanceFile.xlsx")
attendance

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
0,1,"A Cerda, Eddie",1095014,9,2022-2023,169,159,9,3,6,6,27,0,0,1,0
1,1,"A Cerda, Eddie",1095014,9,2022-2023,11,0,0,0,0,0,0,0,0,11,0
2,4,"Aaron, Anastasia",1094167,4,2022-2023,180,179,1,1,0,1,0,0,0,0,0
3,4,"Aaron, Lillie",1095258,1,2022-2023,180,179,1,1,0,1,0,0,0,0,0
4,4,"Aburto-Ramirez, Ayden",1093925,2,2022-2023,180,151,29,29,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,1,"Zuniga, Bailey",1093579,10,2022-2023,180,126,54,24,30,5,85,0,0,0,0
2668,4,"Zuniga, Matthew",1094273,5,2022-2023,180,153,27,19,8,4,9,0,0,0,0
2669,6,"Zuniga, Michelle",1092848,5,2022-2023,180,171,9,7,2,0,2,0,0,0,0
2670,4,"Zuniga, Pedro",1094487,3,2022-2023,180,138,42,13,29,88,69,0,0,0,0
2671,6,"Zuniga Vazquez, Luis",1094375,3,2022-2023,180,172,8,8,0,2,1,0,0,0,0

In [4]:
a = input('What is the school year interest (2021-2022, 2022-2023, etc.):          ')

What is the school year interest (2021-2022, 2022-2023, etc.):          2022-2023

In [5]:
#Making sure that we are only looking at current school year
att = attendance[attendance['Year']== a]
att

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
0,1,"A Cerda, Eddie",1095014,9,2022-2023,169,159,9,3,6,6,27,0,0,1,0
1,1,"A Cerda, Eddie",1095014,9,2022-2023,11,0,0,0,0,0,0,0,0,11,0
2,4,"Aaron, Anastasia",1094167,4,2022-2023,180,179,1,1,0,1,0,0,0,0,0
3,4,"Aaron, Lillie",1095258,1,2022-2023,180,179,1,1,0,1,0,0,0,0,0
4,4,"Aburto-Ramirez, Ayden",1093925,2,2022-2023,180,151,29,29,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,1,"Zuniga, Bailey",1093579,10,2022-2023,180,126,54,24,30,5,85,0,0,0,0
2668,4,"Zuniga, Matthew",1094273,5,2022-2023,180,153,27,19,8,4,9,0,0,0,0
2669,6,"Zuniga, Michelle",1092848,5,2022-2023,180,171,9,7,2,0,2,0,0,0,0
2670,4,"Zuniga, Pedro",1094487,3,2022-2023,180,138,42,13,29,88,69,0,0,0,0
2671,6,"Zuniga Vazquez, Luis",1094375,3,2022-2023,180,172,8,8,0,2,1,0,0,0,0

In [6]:
# Check to see if any students have more than two rows of data
more_than_two = att.groupby(['Student ID']).size()
more_than_two = more_than_two.to_frame()
more_than_two = more_than_two.rename(columns = {0:'Number Rows'}, inplace = False)
more_than_two = more_than_two[more_than_two['Number Rows'] > 2]
more_than_two

Empty DataFrame
Columns: [Number Rows]
Index: []

In [7]:
#Separating duplicated students from the rest and keeping both rows for them
duplicated_students = att[att.duplicated(subset=['Student ID'], keep = False)]
duplicated_students

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
0,1,"A Cerda, Eddie",1095014,9,2022-2023,169,159,9,3,6,6,27,0,0,1,0
1,1,"A Cerda, Eddie",1095014,9,2022-2023,11,0,0,0,0,0,0,0,0,11,0
11,2,"Aceves Barajas, Abel",1093989,8,2022-2023,166,158,8,6,2,0,4,0,0,0,0
12,2,"Aceves Barajas, Abel",1093989,8,2022-2023,14,0,0,0,0,0,0,0,0,14,0
40,1,"Aispuro Sainz, Frida",1092532,11,2022-2023,10,-10,10,0,10,0,10,0,0,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648,1,"Zaragoza, Rihanna",1092514,11,2022-2023,175,158,17,13,4,3,33,0,0,0,0
2650,4,"Zavala, Darren",1094989,2,2022-2023,5,0,0,0,0,0,0,0,0,5,0
2651,4,"Zavala, Darren",1094989,2,2022-2023,175,164,11,11,0,19,1,0,0,0,0
2652,4,"Zavala, Violeta",1095842,-1,2022-2023,5,0,0,0,0,0,0,0,0,5,0
2653,4,"Zavala, Violeta",1095842,-1,2022-2023,175,162,13,13,0,17,1,0,0,0,0

## Getting Students with Duplicated Rows and ISP Attendance

Duplicated students have two rows for them. They have the ones in which they are doing ISP and then their regular attendance at the school In this section, the students are sorted by their Student ID and then enrollment. The lower value represents the days in which they are in ISP so this will be the one that is selected. 

This is done by enrollment since some duplicated students are in home hospital and have no ISP days, so this method will capture these students as well.

In [8]:
# Sorting students by ID and enrollment
students_sorted = duplicated_students.sort_values(['Student ID','Enrolled'])
students_sorted

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2355,1,"Sarabia, Xiomara",1091981,12,2022-2023,9,0,0,0,0,0,0,0,0,9,0
2356,1,"Sarabia, Xiomara",1091981,12,2022-2023,171,162,9,7,2,0,56,0,0,0,0
634,1,"Corea, Belen",1091984,12,2022-2023,10,0,0,0,0,0,0,0,0,10,0
633,1,"Corea, Belen",1091984,12,2022-2023,170,163,7,6,1,0,1,0,0,0,0
532,1,"Cerda, Abraham",1092018,12,2022-2023,7,-7,7,0,7,0,7,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,4,"Dharni, Jasleen",1096019,4,2022-2023,146,132,14,4,10,0,10,0,0,0,0
711,2,"Dharni, Sukhnoor",1096020,7,2022-2023,9,0,0,0,0,0,0,0,0,9,0
710,2,"Dharni, Sukhnoor",1096020,7,2022-2023,145,132,13,1,12,0,17,0,0,0,0
1713,4,"Moreno, Mia",1096021,1,2022-2023,12,0,0,0,0,0,0,0,0,12,0
1714,4,"Moreno, Mia",1096021,1,2022-2023,143,123,20,16,4,8,5,0,0,0,0

In [9]:
# The lowest value row for each student is selected
lowest_number = students_sorted.groupby(['Student ID']).head(1)
lowest_number

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2355,1,"Sarabia, Xiomara",1091981,12,2022-2023,9,0,0,0,0,0,0,0,0,9,0
634,1,"Corea, Belen",1091984,12,2022-2023,10,0,0,0,0,0,0,0,0,10,0
532,1,"Cerda, Abraham",1092018,12,2022-2023,7,-7,7,0,7,0,7,0,0,0,7
889,1,"Gamino, Aileen",1092025,12,2022-2023,4,-4,4,0,4,0,4,0,0,0,4
418,1,"Camacho Hernandez, Yulisa",1092048,12,2022-2023,7,-7,7,0,7,0,7,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1961,2,"Pulido Barajas, Emily",1095995,6,2022-2023,5,0,0,0,0,0,0,0,0,5,0
2324,2,"Sanchez JR, Antonio",1095998,8,2022-2023,5,-5,5,0,5,0,5,0,0,0,5
709,4,"Dharni, Jasleen",1096019,4,2022-2023,9,0,0,0,0,0,0,0,0,9,0
711,2,"Dharni, Sukhnoor",1096020,7,2022-2023,9,0,0,0,0,0,0,0,0,9,0
1713,4,"Moreno, Mia",1096021,1,2022-2023,12,0,0,0,0,0,0,0,0,12,0

In [10]:
# Present column is updated by adding in added days of independent study and incomplete which causes a negative number
lowest_number['Present'] = lowest_number['Present'] + lowest_number['Days of Complete Independent Study'] + lowest_number['Days of Incomplete Independent Study']
lowest_number

C:\Users\DEREK~1.CAS\AppData\Local\Temp/ipykernel_26836/2041064775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lowest_number['Present'] = lowest_number['Present'] + lowest_number['Days of Complete Independent Study'] + lowest_number['Days of Incomplete Independent Study']

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2355,1,"Sarabia, Xiomara",1091981,12,2022-2023,9,9,0,0,0,0,0,0,0,9,0
634,1,"Corea, Belen",1091984,12,2022-2023,10,10,0,0,0,0,0,0,0,10,0
532,1,"Cerda, Abraham",1092018,12,2022-2023,7,0,7,0,7,0,7,0,0,0,7
889,1,"Gamino, Aileen",1092025,12,2022-2023,4,0,4,0,4,0,4,0,0,0,4
418,1,"Camacho Hernandez, Yulisa",1092048,12,2022-2023,7,0,7,0,7,0,7,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1961,2,"Pulido Barajas, Emily",1095995,6,2022-2023,5,5,0,0,0,0,0,0,0,5,0
2324,2,"Sanchez JR, Antonio",1095998,8,2022-2023,5,0,5,0,5,0,5,0,0,0,5
709,4,"Dharni, Jasleen",1096019,4,2022-2023,9,9,0,0,0,0,0,0,0,9,0
711,2,"Dharni, Sukhnoor",1096020,7,2022-2023,9,9,0,0,0,0,0,0,0,9,0
1713,4,"Moreno, Mia",1096021,1,2022-2023,12,12,0,0,0,0,0,0,0,12,0

## Combining Students and Fixing Duplicates

Combining the data that has been fixed in the previous sections. Then concat it to the other duplicates that were filtered out at the beginning. Then merge the rows for each of the students to finally have the data fixed.

In [11]:
students_sorted

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2355,1,"Sarabia, Xiomara",1091981,12,2022-2023,9,0,0,0,0,0,0,0,0,9,0
2356,1,"Sarabia, Xiomara",1091981,12,2022-2023,171,162,9,7,2,0,56,0,0,0,0
634,1,"Corea, Belen",1091984,12,2022-2023,10,0,0,0,0,0,0,0,0,10,0
633,1,"Corea, Belen",1091984,12,2022-2023,170,163,7,6,1,0,1,0,0,0,0
532,1,"Cerda, Abraham",1092018,12,2022-2023,7,-7,7,0,7,0,7,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,4,"Dharni, Jasleen",1096019,4,2022-2023,146,132,14,4,10,0,10,0,0,0,0
711,2,"Dharni, Sukhnoor",1096020,7,2022-2023,9,0,0,0,0,0,0,0,0,9,0
710,2,"Dharni, Sukhnoor",1096020,7,2022-2023,145,132,13,1,12,0,17,0,0,0,0
1713,4,"Moreno, Mia",1096021,1,2022-2023,12,0,0,0,0,0,0,0,0,12,0
1714,4,"Moreno, Mia",1096021,1,2022-2023,143,123,20,16,4,8,5,0,0,0,0

In [12]:
# Getting the other duplicate rows that were filtered out at first
highest_number = students_sorted.groupby(['Student ID']).tail(1)
highest_number

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2356,1,"Sarabia, Xiomara",1091981,12,2022-2023,171,162,9,7,2,0,56,0,0,0,0
633,1,"Corea, Belen",1091984,12,2022-2023,170,163,7,6,1,0,1,0,0,0,0
531,1,"Cerda, Abraham",1092018,12,2022-2023,173,165,8,7,1,2,11,0,0,0,0
890,1,"Gamino, Aileen",1092025,12,2022-2023,176,133,43,32,11,0,20,0,0,0,0
417,1,"Camacho Hernandez, Yulisa",1092048,12,2022-2023,173,163,10,7,3,0,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,2,"Pulido Barajas, Emily",1095995,6,2022-2023,156,140,16,15,1,0,2,0,0,0,0
2325,2,"Sanchez JR, Antonio",1095998,8,2022-2023,152,148,4,2,2,0,3,0,0,0,0
708,4,"Dharni, Jasleen",1096019,4,2022-2023,146,132,14,4,10,0,10,0,0,0,0
710,2,"Dharni, Sukhnoor",1096020,7,2022-2023,145,132,13,1,12,0,17,0,0,0,0
1714,4,"Moreno, Mia",1096021,1,2022-2023,143,123,20,16,4,8,5,0,0,0,0

In [13]:
# Updates present column with days of completed independent study and incomplete since these can be a negative
highest_number['Present'] = highest_number['Present'] + highest_number['Days of Complete Independent Study'] + highest_number['Days of Incomplete Independent Study']
highest_number

C:\Users\DEREK~1.CAS\AppData\Local\Temp/ipykernel_26836/4220912729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highest_number['Present'] = highest_number['Present'] + highest_number['Days of Complete Independent Study'] + highest_number['Days of Incomplete Independent Study']

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
2356,1,"Sarabia, Xiomara",1091981,12,2022-2023,171,162,9,7,2,0,56,0,0,0,0
633,1,"Corea, Belen",1091984,12,2022-2023,170,163,7,6,1,0,1,0,0,0,0
531,1,"Cerda, Abraham",1092018,12,2022-2023,173,165,8,7,1,2,11,0,0,0,0
890,1,"Gamino, Aileen",1092025,12,2022-2023,176,133,43,32,11,0,20,0,0,0,0
417,1,"Camacho Hernandez, Yulisa",1092048,12,2022-2023,173,163,10,7,3,0,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1962,2,"Pulido Barajas, Emily",1095995,6,2022-2023,156,140,16,15,1,0,2,0,0,0,0
2325,2,"Sanchez JR, Antonio",1095998,8,2022-2023,152,148,4,2,2,0,3,0,0,0,0
708,4,"Dharni, Jasleen",1096019,4,2022-2023,146,132,14,4,10,0,10,0,0,0,0
710,2,"Dharni, Sukhnoor",1096020,7,2022-2023,145,132,13,1,12,0,17,0,0,0,0
1714,4,"Moreno, Mia",1096021,1,2022-2023,143,123,20,16,4,8,5,0,0,0,0

In [14]:
# Combining data to recreate the duplicated rows for each student
combined_duplicated = pd.concat([highest_number, lowest_number]).sort_values(['Student ID','Enrolled'], ascending=False)
combined_duplicated

,School,Student Name,Student ID,Grade,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
1714,4,"Moreno, Mia",1096021,1,2022-2023,143,123,20,16,4,8,5,0,0,0,0
1713,4,"Moreno, Mia",1096021,1,2022-2023,12,12,0,0,0,0,0,0,0,12,0
710,2,"Dharni, Sukhnoor",1096020,7,2022-2023,145,132,13,1,12,0,17,0,0,0,0
711,2,"Dharni, Sukhnoor",1096020,7,2022-2023,9,9,0,0,0,0,0,0,0,9,0
708,4,"Dharni, Jasleen",1096019,4,2022-2023,146,132,14,4,10,0,10,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,1,"Cerda, Abraham",1092018,12,2022-2023,7,0,7,0,7,0,7,0,0,0,7
633,1,"Corea, Belen",1091984,12,2022-2023,170,163,7,6,1,0,1,0,0,0,0
634,1,"Corea, Belen",1091984,12,2022-2023,10,10,0,0,0,0,0,0,0,10,0
2356,1,"Sarabia, Xiomara",1091981,12,2022-2023,171,162,9,7,2,0,56,0,0,0,0
2355,1,"Sarabia, Xiomara",1091981,12,2022-2023,9,9,0,0,0,0,0,0,0,9,0

In [15]:
# Merging the two rows for each student to create one single entry with the corrected data
Schoolfixed_absent = combined_duplicated.groupby(['Student Name','Grade','Student ID', 'School', 'Year']).sum().reset_index()

In [16]:
Schoolfixed_absent

,Student Name,Grade,Student ID,School,Year,Enrolled,Present,Absences,Excused,Unexcused,Tardies,Days of Truancy,Days of Suspension,Days of In School Suspension,Days of Complete Independent Study,Days of Incomplete Independent Study
0,"A Cerda, Eddie",9,1095014,1,2022-2023,180,171,9,3,6,6,27,0,0,12,0
1,"Aceves Barajas, Abel",8,1093989,2,2022-2023,180,172,8,6,2,0,4,0,0,14,0
2,"Aispuro Sainz, Frida",11,1092532,1,2022-2023,180,135,45,26,19,17,41,0,0,0,10
3,"Almazan, Isaac",5,1093452,6,2022-2023,180,173,7,5,2,0,2,0,0,10,0
4,"Almazan, Marlyn",8,1093461,7,2022-2023,180,178,2,2,0,0,6,0,0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,"Zandejas, Jonael",1,1095424,4,2022-2023,180,180,0,0,0,0,0,0,0,10,0
223,"Zaragoza, Arianna",11,1092513,1,2022-2023,180,167,13,8,5,4,27,0,0,5,0
224,"Zaragoza, Rihanna",11,1092514,1,2022-2023,180,163,17,13,4,3,33,0,0,5,0
225,"Zavala, Darren",2,1094989,4,2022-2023,180,169,11,11,0,19,1,0,0,5,0
226,"Zavala, Violeta",-1,1095842,4,2022-2023,180,167,13,13,0,17,1,0,0,5,0

In [17]:
# Checking to see if any unduplicated rows still remain
duplicated_students = Schoolfixed_absent[Schoolfixed_absent.duplicated(subset=['Student ID'], keep = False)]
duplicated_students

Empty DataFrame
Columns: [Student Name, Grade, Student ID, School, Year, Enrolled, Present, Absences, Excused, Unexcused, Tardies, Days of Truancy, Days of Suspension, Days of In School Suspension, Days of Complete Independent Study, Days of Incomplete Independent Study]
Index: []

## Attendance with Single Line for Students

The file generated here has one row for each student with the ISP corrected as days present for the student for cases in which we want to see the full attendance for a student.

In [18]:
# Generates a csv file from the final dataframe
import base64
from IPython.display import HTML

def create_download_link( df, title = "Attendance Fixed", filename = "Attendance Fixed"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

create_download_link(Schoolfixed_absent)

## Attendance with ISP Separated

The file generated here has the ISP rows still separated but are now corrected so that the completed study shows as being days present and the incomplete days no longer show as a negative number on attendance.

In [19]:
# Generates a csv file from the final dataframe
import base64
from IPython.display import HTML

def create_download_link( df, title = "Attendance ISP Fixed", filename = "Attendance ISP Fixed"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

create_download_link(combined_duplicated)